version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: nginx:latest
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Nifleheim/landing-page/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  lp:

    executor: my-custom-executor
    steps:
      - checkout
      - run: npm start

workflows:
  my-custom-workflow:
    jobs:
      - lp
